from django.db import models

class Bungalow(models.Model):
    area_unit = models.CharField(max_length=5, blank=True)
    bathrooms = models.DecimalField(max_digits=10, decimal_places=1, null=True, blank=True)
    bedrooms = models.IntegerField(null=True, blank=True)
    home_size = models.IntegerField(null=True, blank=True)
    home_type = models.CharField(max_length=50, blank=True)
    last_sold_date = models.DateTimeField(null=True, blank=True)
    last_sold_price = models.IntegerField(null=True, blank=True)
    link = models.TextField(blank=True)
    price = models.CharField(max_length=20, blank=True)
    property_size = models.IntegerField(null=True, blank=True)
    rent_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    rentzestimate_amount =  models.IntegerField(null=True, blank=True)
    rentzestimate_last_updated = models.DateTimeField(null=True, blank=True)
    tax_value = models.IntegerField(null=True, blank=True)
    tax_year = models.IntegerField(null=True, blank=True)
    year_built = models.IntegerField(null=True, blank=True)
    zestimate_amount = models.IntegerField(null=True, blank=True)
    zestimate_last_updated = models.DateTimeField(null=True, blank=True)
    zillow_id =  models.IntegerField(null=True, blank=True)
    address = models.TextField(blank=True)
    city = models.CharField(max_length=25, blank=True)
    state = models.CharField(max_length=2, blank=True)
    zipcode = models.CharField(max_length=5, blank=True)